version: '3.4'

services:
  myexpressapp:
    container_name: kneeTrainerAPI
    restart: always
    # image: kneetrainer-api-server-dev:development
    build:
      context: ./webIOTServerExpressJS/
      dockerfile: ./Dockerfile.dev
    stdin_open: true
    volumes:
      -  api_node_modules:/usr/src/api/node_modules
      - ./database/:/usr/src/api/database/
    ports:
      - "5000:5000"
    networks:
      - webIOTtrainer

  myreactapp:
    container_name: kneeTrainerClient
    restart: always
    # image: kneetrainer-app-client-dev:development
    build:
      context: ./webIOTReactFront/
      dockerfile: ./Dockerfile
    stdin_open: true
    environment:
      - REACT_APP_API_URL=myexpressapp:5000
    ports:
      - "3000:3000"
    networks:
      - webIOTtrainer
    volumes:
      - ./caddy_data:/data
      - ./caddy_config:/config
    depends_on:
      - myexpressapp
    
networks:
  webIOTtrainer:
    driver: bridge

volumes:
  api_node_modules: